# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '2.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow2(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1213, 376)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(220, 60, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(50, 60, 113, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 40, 141, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(50, 300, 201, 16))
        self.label_2.setObjectName("label_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(50, 320, 113, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget_2.setEnabled(False)
        self.tableWidget_2.setGeometry(QtCore.QRect(20, 110, 1181, 151))
        self.tableWidget_2.setRowCount(5)
        self.tableWidget_2.setColumnCount(32)
        self.tableWidget_2.setObjectName("tableWidget_2")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(0, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(0, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(0, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(0, 7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(0, 8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(0, 9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(0, 10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(0, 11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(0, 12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(0, 13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(0, 14, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(0, 15, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(0, 16, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(0, 17, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(1, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(1, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(1, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(1, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(1, 7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(1, 8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(1, 9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(1, 10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(1, 11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(1, 12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(1, 13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(1, 14, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(1, 15, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(1, 16, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(1, 17, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(1, 18, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(1, 19, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(1, 20, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(1, 21, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(1, 22, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(1, 25, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(1, 26, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(1, 27, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(1, 28, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(1, 29, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(1, 30, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(2, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(2, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(2, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(2, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(2, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(2, 7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(2, 8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(2, 9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(2, 10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(2, 11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(2, 12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(2, 13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(2, 14, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(2, 15, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(2, 16, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(2, 17, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(2, 18, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(2, 19, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(2, 20, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(2, 21, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(2, 22, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(2, 23, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(2, 24, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(2, 25, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(2, 26, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(2, 27, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(2, 28, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(2, 29, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(2, 30, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(2, 31, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(3, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(3, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(3, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(3, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(3, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(3, 7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(3, 8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(3, 9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(3, 10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(3, 11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(3, 12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(3, 13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(3, 14, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(3, 15, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(3, 16, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(3, 17, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(3, 18, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(3, 19, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(3, 20, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(3, 21, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(3, 22, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(3, 23, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(3, 24, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(3, 25, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(3, 26, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(3, 27, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(3, 28, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(3, 29, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(3, 30, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(3, 31, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(4, 0, item)
        self.tableWidget_2.horizontalHeader().setVisible(False)
        self.tableWidget_2.horizontalHeader().setDefaultSectionSize(36)
        self.tableWidget_2.horizontalHeader().setHighlightSections(True)
        self.tableWidget_2.horizontalHeader().setMinimumSectionSize(26)
        self.tableWidget_2.verticalHeader().setVisible(False)
        self.tableWidget_2.verticalHeader().setDefaultSectionSize(28)
        self.tableWidget_2.verticalHeader().setMinimumSectionSize(24)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "float"))
        self.pushButton.setText(_translate("MainWindow", "Перевод"))
        self.label.setText(_translate("MainWindow", "Число"))
        self.label_2.setText(_translate("MainWindow", "Обратный побитовый перевод"))
        __sortingEnabled = self.tableWidget_2.isSortingEnabled()
        self.tableWidget_2.setSortingEnabled(False)
        item = self.tableWidget_2.item(0, 1)
        item.setText(_translate("MainWindow", "Знак"))
        item = self.tableWidget_2.item(0, 2)
        item.setText(_translate("MainWindow", "Х"))
        item = self.tableWidget_2.item(0, 3)
        item.setText(_translate("MainWindow", "А"))
        item = self.tableWidget_2.item(0, 4)
        item.setText(_translate("MainWindow", "Р"))
        item = self.tableWidget_2.item(0, 5)
        item.setText(_translate("MainWindow", "А"))
        item = self.tableWidget_2.item(0, 6)
        item.setText(_translate("MainWindow", "К"))
        item = self.tableWidget_2.item(0, 7)
        item.setText(_translate("MainWindow", "Т"))
        item = self.tableWidget_2.item(0, 8)
        item.setText(_translate("MainWindow", "Е"))
        item = self.tableWidget_2.item(0, 9)
        item.setText(_translate("MainWindow", "Р"))
        item = self.tableWidget_2.item(0, 10)
        item.setText(_translate("MainWindow", "М"))
        item = self.tableWidget_2.item(0, 11)
        item.setText(_translate("MainWindow", "А"))
        item = self.tableWidget_2.item(0, 12)
        item.setText(_translate("MainWindow", "Н"))
        item = self.tableWidget_2.item(0, 13)
        item.setText(_translate("MainWindow", "Т"))
        item = self.tableWidget_2.item(0, 14)
        item.setText(_translate("MainWindow", "И"))
        item = self.tableWidget_2.item(0, 15)
        item.setText(_translate("MainWindow", "С"))
        item = self.tableWidget_2.item(0, 16)
        item.setText(_translate("MainWindow", "С"))
        item = self.tableWidget_2.item(0, 17)
        item.setText(_translate("MainWindow", "А"))
        item = self.tableWidget_2.item(1, 0)
        item.setText(_translate("MainWindow", "Байт"))
        item = self.tableWidget_2.item(1, 1)
        item.setText(_translate("MainWindow", "Б"))
        item = self.tableWidget_2.item(1, 2)
        item.setText(_translate("MainWindow", "А"))
        item = self.tableWidget_2.item(1, 3)
        item.setText(_translate("MainWindow", "Й"))
        item = self.tableWidget_2.item(1, 4)
        item.setText(_translate("MainWindow", "Т"))
        item = self.tableWidget_2.item(1, 5)
        item.setText(_translate("MainWindow", "№"))
        item = self.tableWidget_2.item(1, 6)
        item.setText(_translate("MainWindow", "3"))
        item = self.tableWidget_2.item(1, 9)
        item.setText(_translate("MainWindow", "Б"))
        item = self.tableWidget_2.item(1, 10)
        item.setText(_translate("MainWindow", "А"))
        item = self.tableWidget_2.item(1, 11)
        item.setText(_translate("MainWindow", "Й"))
        item = self.tableWidget_2.item(1, 12)
        item.setText(_translate("MainWindow", "Т"))
        item = self.tableWidget_2.item(1, 13)
        item.setText(_translate("MainWindow", "№"))
        item = self.tableWidget_2.item(1, 14)
        item.setText(_translate("MainWindow", "2"))
        item = self.tableWidget_2.item(1, 17)
        item.setText(_translate("MainWindow", "Б"))
        item = self.tableWidget_2.item(1, 18)
        item.setText(_translate("MainWindow", "А"))
        item = self.tableWidget_2.item(1, 19)
        item.setText(_translate("MainWindow", "Й"))
        item = self.tableWidget_2.item(1, 20)
        item.setText(_translate("MainWindow", "Т"))
        item = self.tableWidget_2.item(1, 21)
        item.setText(_translate("MainWindow", "№"))
        item = self.tableWidget_2.item(1, 22)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget_2.item(1, 25)
        item.setText(_translate("MainWindow", "Б"))
        item = self.tableWidget_2.item(1, 26)
        item.setText(_translate("MainWindow", "А"))
        item = self.tableWidget_2.item(1, 27)
        item.setText(_translate("MainWindow", "Й"))
        item = self.tableWidget_2.item(1, 28)
        item.setText(_translate("MainWindow", "Т"))
        item = self.tableWidget_2.item(1, 29)
        item.setText(_translate("MainWindow", "№"))
        item = self.tableWidget_2.item(1, 30)
        item.setText(_translate("MainWindow", "0"))
        item = self.tableWidget_2.item(2, 0)
        item.setText(_translate("MainWindow", "№ бита"))
        item = self.tableWidget_2.item(2, 1)
        item.setText(_translate("MainWindow", "31"))
        item = self.tableWidget_2.item(2, 2)
        item.setText(_translate("MainWindow", "30"))
        item = self.tableWidget_2.item(2, 3)
        item.setText(_translate("MainWindow", "29"))
        item = self.tableWidget_2.item(2, 4)
        item.setText(_translate("MainWindow", "28"))
        item = self.tableWidget_2.item(2, 5)
        item.setText(_translate("MainWindow", "27"))
        item = self.tableWidget_2.item(2, 6)
        item.setText(_translate("MainWindow", "26"))
        item = self.tableWidget_2.item(2, 7)
        item.setText(_translate("MainWindow", "25"))
        item = self.tableWidget_2.item(2, 8)
        item.setText(_translate("MainWindow", "24"))
        item = self.tableWidget_2.item(2, 9)
        item.setText(_translate("MainWindow", "23"))
        item = self.tableWidget_2.item(2, 10)
        item.setText(_translate("MainWindow", "22"))
        item = self.tableWidget_2.item(2, 11)
        item.setText(_translate("MainWindow", "21"))
        item = self.tableWidget_2.item(2, 12)
        item.setText(_translate("MainWindow", "20"))
        item = self.tableWidget_2.item(2, 13)
        item.setText(_translate("MainWindow", "19"))
        item = self.tableWidget_2.item(2, 14)
        item.setText(_translate("MainWindow", "18"))
        item = self.tableWidget_2.item(2, 15)
        item.setText(_translate("MainWindow", "17"))
        item = self.tableWidget_2.item(2, 16)
        item.setText(_translate("MainWindow", "16"))
        item = self.tableWidget_2.item(2, 17)
        item.setText(_translate("MainWindow", "15"))
        item = self.tableWidget_2.item(2, 18)
        item.setText(_translate("MainWindow", "14"))
        item = self.tableWidget_2.item(2, 19)
        item.setText(_translate("MainWindow", "13"))
        item = self.tableWidget_2.item(2, 20)
        item.setText(_translate("MainWindow", "12"))
        item = self.tableWidget_2.item(2, 21)
        item.setText(_translate("MainWindow", "11"))
        item = self.tableWidget_2.item(2, 22)
        item.setText(_translate("MainWindow", "10"))
        item = self.tableWidget_2.item(2, 23)
        item.setText(_translate("MainWindow", "9"))
        item = self.tableWidget_2.item(2, 24)
        item.setText(_translate("MainWindow", "8"))
        item = self.tableWidget_2.item(2, 25)
        item.setText(_translate("MainWindow", "7"))
        item = self.tableWidget_2.item(2, 26)
        item.setText(_translate("MainWindow", "6"))
        item = self.tableWidget_2.item(2, 27)
        item.setText(_translate("MainWindow", "5"))
        item = self.tableWidget_2.item(2, 28)
        item.setText(_translate("MainWindow", "4"))
        item = self.tableWidget_2.item(2, 29)
        item.setText(_translate("MainWindow", "3"))
        item = self.tableWidget_2.item(2, 30)
        item.setText(_translate("MainWindow", "2"))
        item = self.tableWidget_2.item(2, 31)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget_2.item(3, 0)
        item.setText(_translate("MainWindow", "Вес бита"))
        item = self.tableWidget_2.item(3, 1)
        item.setText(_translate("MainWindow", "256"))
        item = self.tableWidget_2.item(3, 2)
        item.setText(_translate("MainWindow", "128"))
        item = self.tableWidget_2.item(3, 3)
        item.setText(_translate("MainWindow", "64"))
        item = self.tableWidget_2.item(3, 4)
        item.setText(_translate("MainWindow", "32"))
        item = self.tableWidget_2.item(3, 5)
        item.setText(_translate("MainWindow", "16"))
        item = self.tableWidget_2.item(3, 6)
        item.setText(_translate("MainWindow", "8"))
        item = self.tableWidget_2.item(3, 7)
        item.setText(_translate("MainWindow", "4"))
        item = self.tableWidget_2.item(3, 8)
        item.setText(_translate("MainWindow", "2"))
        item = self.tableWidget_2.item(3, 9)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget_2.item(3, 10)
        item.setText(_translate("MainWindow", "0.5"))
        item = self.tableWidget_2.item(3, 11)
        item.setText(_translate("MainWindow", "0.25"))
        item = self.tableWidget_2.item(3, 12)
        item.setText(_translate("MainWindow", "0.125"))
        item = self.tableWidget_2.item(3, 13)
        item.setText(_translate("MainWindow", "0.0625"))
        item = self.tableWidget_2.item(3, 14)
        item.setText(_translate("MainWindow", "0.0625"))
        item = self.tableWidget_2.item(3, 15)
        item.setText(_translate("MainWindow", "0.0625"))
        item = self.tableWidget_2.item(3, 16)
        item.setText(_translate("MainWindow", "0.0625"))
        item = self.tableWidget_2.item(3, 17)
        item.setText(_translate("MainWindow", "0.0625"))
        item = self.tableWidget_2.item(3, 18)
        item.setText(_translate("MainWindow", "0.0625"))
        item = self.tableWidget_2.item(3, 19)
        item.setText(_translate("MainWindow", "0.0625"))
        item = self.tableWidget_2.item(3, 20)
        item.setText(_translate("MainWindow", "0.0625"))
        item = self.tableWidget_2.item(3, 21)
        item.setText(_translate("MainWindow", "0.0625"))
        item = self.tableWidget_2.item(3, 22)
        item.setText(_translate("MainWindow", "0.0625"))
        item = self.tableWidget_2.item(3, 23)
        item.setText(_translate("MainWindow", "0.0625"))
        item = self.tableWidget_2.item(3, 24)
        item.setText(_translate("MainWindow", "0.0625"))
        item = self.tableWidget_2.item(3, 25)
        item.setText(_translate("MainWindow", "0.0625"))
        item = self.tableWidget_2.item(3, 26)
        item.setText(_translate("MainWindow", "0.0625"))
        item = self.tableWidget_2.item(3, 27)
        item.setText(_translate("MainWindow", "0.0625"))
        item = self.tableWidget_2.item(3, 28)
        item.setText(_translate("MainWindow", "0.0625"))
        item = self.tableWidget_2.item(3, 29)
        item.setText(_translate("MainWindow", "0.0625"))
        item = self.tableWidget_2.item(3, 30)
        item.setText(_translate("MainWindow", "0.0625"))
        item = self.tableWidget_2.item(3, 31)
        item.setText(_translate("MainWindow", "0.0625"))
        item = self.tableWidget_2.item(4, 0)
        item.setText(_translate("MainWindow", "бит"))
        self.tableWidget_2.setSortingEnabled(__sortingEnabled)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
