# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'P3_ui.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5.QtWidgets import QApplication, QMainWindow, QGridLayout, QWidget, QTableWidget, QTableWidgetItem
from PyQt5 import QtCore, QtGui, QtWidgets
import struct

getBin = lambda x: x > 0 and str(bin(x))[2:] or "-" + str(bin(x))[3:]
def floatToBinary(value):return getBin(struct.unpack('Q',struct.pack("f", value) + b"\x00\x00\x00\x00")[0])
def binaryToFloat(value):   return  struct.unpack("f",struct.pack("q", int(value, 2))[:-4])[0]
def doubleToBinary(value):return getBin(struct.unpack('Q',struct.pack("d", value))[0])
def binaryToDouble(value):   return  struct.unpack("d",struct.pack("q", int(value, 2)))[0]

class Ui_MainWindow(object):
    def open_win1(self):
        self.window = QtWidgets.QMainWindow()
        self.ui =  Ui_MainWindow1()
        self.ui.setupUi(self.window)
        self.window.show()

    def open_win2(self):
        self.window = QtWidgets.QMainWindow()
        self.ui =  Ui_MainWindow2()
        self.ui.setupUi(self.window)
        self.window.show()

    def open_win3(self):
        self.window = QtWidgets.QMainWindow()
        self.ui =  Ui_MainWindow3()
        self.ui.setupUi(self.window)
        self.window.show()
    def open_win4(self):
        self.window = QtWidgets.QMainWindow()
        self.ui =  Ui_MainWindow4()
        self.ui.setupUi(self.window)
        self.window.show()

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(313, 242)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 313, 21))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menu)
        self.menu_2.setObjectName("menu_2")
        MainWindow.setMenuBar(self.menubar)
        self.action = QtWidgets.QAction(MainWindow)
        self.action.setObjectName("action")
        self.action.triggered.connect(self.open_win1)
        self.action_3 = QtWidgets.QAction(MainWindow)
        self.action_3.setObjectName("action_3")
        self.action_3.triggered.connect(self.open_win4)
        self.action_4 = QtWidgets.QAction(MainWindow)
        self.action_4.setObjectName("action_4")
        self.action_4.triggered.connect(self.open_win2)
        self.action_5 = QtWidgets.QAction(MainWindow)
        self.action_5.setObjectName("action_5")
        self.action_5.triggered.connect(self.open_win3)
        self.menu_2.addAction(self.action_4)
        self.menu_2.addAction(self.action_5)
        self.menu.addAction(self.action)
        self.menu.addAction(self.menu_2.menuAction())
        self.menu.addAction(self.action_3)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Простые переменные"))
        self.menu.setTitle(_translate("MainWindow", "Переменные"))
        self.menu_2.setTitle(_translate("MainWindow", "Вещественные"))
        self.action.setText(_translate("MainWindow", "Целочисленные"))
        self.action_3.setText(_translate("MainWindow", "Символьные"))
        self.action_4.setText(_translate("MainWindow", "Одинарной точности"))
        self.action_5.setText(_translate("MainWindow", "Двойной точности"))

class Ui_MainWindow1(object):

    def eval(self):
        print("1")
        self.bin = bin(int(self.lineEdit.text()))
        self.znak = 0 if self.bin[0]=="0" else 1
        print(self.bin)
        self.tableWidget.setItem(1,1, QTableWidgetItem(str(self.znak)))

        self.flag = True
        for i in range(8):
            if self.bin[-i] == "b": self.flag = False

            if self.flag: self.tableWidget.setItem(1, 9-i, QTableWidgetItem(self.bin[-i]))
            else: self.tableWidget.setItem(1, 9-i, QTableWidgetItem("0"))
            print(i)

        print("2")
        self.lineEdit_2.setText(self.lineEdit.text())


    def left(self):
        try:
            self.lineEdit.setText(str(int(self.lineEdit.text()) << 1))
            self.eval()
        except Exception as err: print(err)


    def right(self):
        try:
            self.lineEdit.setText(str(int(self.lineEdit.text()) >> 1))
            self.eval()
        except Exception as err: print(err)

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(435, 341)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(330, 60, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.left)
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.clicked.connect(self.right)
        self.pushButton_2.setGeometry(QtCore.QRect(330, 90, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(40, 60, 113, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 40, 141, 16))
        self.label.setObjectName("label")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setEnabled(False)
        self.tableWidget.setGeometry(QtCore.QRect(20, 150, 381, 71))
        self.tableWidget.setRowCount(2)
        self.tableWidget.setColumnCount(9)
        self.tableWidget.setObjectName("tableWidget")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 0, item)
        self.tableWidget.horizontalHeader().setVisible(False)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(41)
        self.tableWidget.horizontalHeader().setHighlightSections(True)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(26)
        self.tableWidget.verticalHeader().setVisible(False)
        self.tableWidget.verticalHeader().setDefaultSectionSize(31)
        self.tableWidget.verticalHeader().setMinimumSectionSize(24)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(30, 290, 171, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(240, 290, 151, 23))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_3.clicked.connect(self.eval)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(60, 130, 31, 16))
        self.label_2.setAutoFillBackground(False)
        self.label_2.setStyleSheet("background-color : red")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(100, 130, 291, 16))
        self.label_3.setStyleSheet("background-color : yellow")
        self.label_3.setObjectName("label_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "byte"))
        self.pushButton.setText(_translate("MainWindow", "<<"))
        self.pushButton_2.setText(_translate("MainWindow", ">>"))
        self.label.setText(_translate("MainWindow", "Число в десятичной СС"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("MainWindow", "Вес бита"))
        item = self.tableWidget.item(0, 1)
        item.setText(_translate("MainWindow", "128"))
        item = self.tableWidget.item(0, 2)
        item.setText(_translate("MainWindow", "64"))
        item = self.tableWidget.item(0, 3)
        item.setText(_translate("MainWindow", "32"))
        item = self.tableWidget.item(0, 4)
        item.setText(_translate("MainWindow", "16"))
        item = self.tableWidget.item(0, 5)
        item.setText(_translate("MainWindow", "8"))
        item = self.tableWidget.item(0, 6)
        item.setText(_translate("MainWindow", "4"))
        item = self.tableWidget.item(0, 7)
        item.setText(_translate("MainWindow", "2"))
        item = self.tableWidget.item(0, 8)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget.item(1, 0)
        item.setText(_translate("MainWindow", "Значение"))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.pushButton_3.setText(_translate("MainWindow", "Перевод"))
        self.label_2.setText(_translate("MainWindow", "Знак"))
        self.label_3.setText(_translate("MainWindow", "Биты числа"))

class Ui_MainWindow2(object):



    def eval(self):
        self.bin = floatToBinary(float(self.lineEdit.text()))

        if(len(self.bin)==31): self.bin = "0"+self.bin
        self.flag = False

        for i in range(32)[::-1]:
            print(i)
            if self.bin[i] =="1":
                self.flag = True
            if self.flag:
                self.tableWidget_2.setItem(4, i+1, QTableWidgetItem(str(self.bin[i])))

        self.lineEdit_2.setText(str(binaryToFloat(self.bin)))

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1400, 376)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.clicked.connect(self.eval)
        self.pushButton.setGeometry(QtCore.QRect(220, 60, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(50, 60, 113, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 40, 141, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(50, 300, 201, 16))
        self.label_2.setObjectName("label_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(50, 320, 113, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget_2.setEnabled(False)
        self.tableWidget_2.setGeometry(QtCore.QRect(20, 110, 1300, 151))
        self.tableWidget_2.setRowCount(5)
        self.tableWidget_2.setColumnCount(33)
        self.tableWidget_2.setObjectName("tableWidget_2")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(0, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(0, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(0, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(0, 7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(0, 8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(0, 9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(0, 10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(0, 11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(0, 12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(0, 13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(0, 14, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(0, 15, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(0, 16, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(0, 17, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(1, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(1, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(1, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(1, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(1, 7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(1, 8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(1, 9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(1, 10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(1, 11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(1, 12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(1, 13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(1, 14, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(1, 15, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(1, 16, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(1, 17, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(1, 18, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(1, 19, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(1, 20, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(1, 21, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(1, 22, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(1, 25, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(1, 26, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(1, 27, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(1, 28, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(1, 29, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(1, 30, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(2, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(2, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(2, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(2, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(2, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(2, 7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(2, 8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(2, 9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(2, 10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(2, 11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(2, 12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(2, 13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(2, 14, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(2, 15, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(2, 16, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(2, 17, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(2, 18, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(2, 19, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(2, 20, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(2, 21, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(2, 22, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(2, 23, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(2, 24, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(2, 25, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(2, 26, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(2, 27, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(2, 28, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(2, 29, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(2, 30, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(2, 31, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(3, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(3, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(3, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(3, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(3, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(3, 7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(3, 8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(3, 9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(3, 10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(3, 11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(3, 12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(3, 13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(3, 14, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(3, 15, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(3, 16, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(3, 17, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(3, 18, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(3, 19, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(3, 20, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(3, 21, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(3, 22, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(3, 23, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(3, 24, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(3, 25, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(3, 26, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(3, 27, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(3, 28, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(3, 29, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(3, 30, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(3, 31, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(1, 32, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(2, 32, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(3, 32, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(4, 0, item)
        self.tableWidget_2.horizontalHeader().setVisible(False)
        self.tableWidget_2.horizontalHeader().setDefaultSectionSize(15)
        self.tableWidget_2.horizontalHeader().setHighlightSections(True)
        self.tableWidget_2.horizontalHeader().setMinimumSectionSize(14)
        self.tableWidget_2.verticalHeader().setVisible(False)
        self.tableWidget_2.verticalHeader().setDefaultSectionSize(13)
        self.tableWidget_2.verticalHeader().setMinimumSectionSize(13)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "float"))
        self.pushButton.setText(_translate("MainWindow", "Перевод"))
        self.label.setText(_translate("MainWindow", "Число"))
        self.label_2.setText(_translate("MainWindow", "Обратный побитовый перевод"))
        __sortingEnabled = self.tableWidget_2.isSortingEnabled()
        self.tableWidget_2.setSortingEnabled(False)
        item = self.tableWidget_2.item(0, 1)
        item.setText(_translate("MainWindow", "Знак"))
        item = self.tableWidget_2.item(0, 2)
        item.setText(_translate("MainWindow", "Х"))
        item = self.tableWidget_2.item(0, 3)
        item.setText(_translate("MainWindow", "А"))
        item = self.tableWidget_2.item(0, 4)
        item.setText(_translate("MainWindow", "Р"))
        item = self.tableWidget_2.item(0, 5)
        item.setText(_translate("MainWindow", "А"))
        item = self.tableWidget_2.item(0, 6)
        item.setText(_translate("MainWindow", "К"))
        item = self.tableWidget_2.item(0, 7)
        item.setText(_translate("MainWindow", "Т"))
        item = self.tableWidget_2.item(0, 8)
        item.setText(_translate("MainWindow", "Е"))
        item = self.tableWidget_2.item(0, 9)
        item.setText(_translate("MainWindow", "Р"))
        item = self.tableWidget_2.item(0, 10)
        item.setText(_translate("MainWindow", "М"))
        item = self.tableWidget_2.item(0, 11)
        item.setText(_translate("MainWindow", "А"))
        item = self.tableWidget_2.item(0, 12)
        item.setText(_translate("MainWindow", "Н"))
        item = self.tableWidget_2.item(0, 13)
        item.setText(_translate("MainWindow", "Т"))
        item = self.tableWidget_2.item(0, 14)
        item.setText(_translate("MainWindow", "И"))
        item = self.tableWidget_2.item(0, 15)
        item.setText(_translate("MainWindow", "С"))
        item = self.tableWidget_2.item(0, 16)
        item.setText(_translate("MainWindow", "С"))
        item = self.tableWidget_2.item(0, 17)
        item.setText(_translate("MainWindow", "А"))
        item = self.tableWidget_2.item(1, 0)
        item.setText(_translate("MainWindow", "Байт"))
        item = self.tableWidget_2.item(1, 1)
        item.setText(_translate("MainWindow", "Б"))
        item = self.tableWidget_2.item(1, 2)
        item.setText(_translate("MainWindow", "А"))
        item = self.tableWidget_2.item(1, 3)
        item.setText(_translate("MainWindow", "Й"))
        item = self.tableWidget_2.item(1, 4)
        item.setText(_translate("MainWindow", "Т"))
        item = self.tableWidget_2.item(1, 5)
        item.setText(_translate("MainWindow", "№"))
        item = self.tableWidget_2.item(1, 6)
        item.setText(_translate("MainWindow", "3"))
        item = self.tableWidget_2.item(1, 9)
        item.setText(_translate("MainWindow", "Б"))
        item = self.tableWidget_2.item(1, 10)
        item.setText(_translate("MainWindow", "А"))
        item = self.tableWidget_2.item(1, 11)
        item.setText(_translate("MainWindow", "Й"))
        item = self.tableWidget_2.item(1, 12)
        item.setText(_translate("MainWindow", "Т"))
        item = self.tableWidget_2.item(1, 13)
        item.setText(_translate("MainWindow", "№"))
        item = self.tableWidget_2.item(1, 14)
        item.setText(_translate("MainWindow", "2"))
        item = self.tableWidget_2.item(1, 17)
        item.setText(_translate("MainWindow", "Б"))
        item = self.tableWidget_2.item(1, 18)
        item.setText(_translate("MainWindow", "А"))
        item = self.tableWidget_2.item(1, 19)
        item.setText(_translate("MainWindow", "Й"))
        item = self.tableWidget_2.item(1, 20)
        item.setText(_translate("MainWindow", "Т"))
        item = self.tableWidget_2.item(1, 21)
        item.setText(_translate("MainWindow", "№"))
        item = self.tableWidget_2.item(1, 22)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget_2.item(1, 25)
        item.setText(_translate("MainWindow", "Б"))
        item = self.tableWidget_2.item(1, 26)
        item.setText(_translate("MainWindow", "А"))
        item = self.tableWidget_2.item(1, 27)
        item.setText(_translate("MainWindow", "Й"))
        item = self.tableWidget_2.item(1, 28)
        item.setText(_translate("MainWindow", "Т"))
        item = self.tableWidget_2.item(1, 29)
        item.setText(_translate("MainWindow", "№"))
        item = self.tableWidget_2.item(1, 30)
        item.setText(_translate("MainWindow", "0"))
        item = self.tableWidget_2.item(2, 0)
        item.setText(_translate("MainWindow", "№ бита"))
        item = self.tableWidget_2.item(2, 1)
        item.setText(_translate("MainWindow", "31"))
        item = self.tableWidget_2.item(2, 2)
        item.setText(_translate("MainWindow", "30"))
        item = self.tableWidget_2.item(2, 3)
        item.setText(_translate("MainWindow", "29"))
        item = self.tableWidget_2.item(2, 4)
        item.setText(_translate("MainWindow", "28"))
        item = self.tableWidget_2.item(2, 5)
        item.setText(_translate("MainWindow", "27"))
        item = self.tableWidget_2.item(2, 6)
        item.setText(_translate("MainWindow", "26"))
        item = self.tableWidget_2.item(2, 7)
        item.setText(_translate("MainWindow", "25"))
        item = self.tableWidget_2.item(2, 8)
        item.setText(_translate("MainWindow", "24"))
        item = self.tableWidget_2.item(2, 9)
        item.setText(_translate("MainWindow", "23"))
        item = self.tableWidget_2.item(2, 10)
        item.setText(_translate("MainWindow", "22"))
        item = self.tableWidget_2.item(2, 11)
        item.setText(_translate("MainWindow", "21"))
        item = self.tableWidget_2.item(2, 12)
        item.setText(_translate("MainWindow", "20"))
        item = self.tableWidget_2.item(2, 13)
        item.setText(_translate("MainWindow", "19"))
        item = self.tableWidget_2.item(2, 14)
        item.setText(_translate("MainWindow", "18"))
        item = self.tableWidget_2.item(2, 15)
        item.setText(_translate("MainWindow", "17"))
        item = self.tableWidget_2.item(2, 16)
        item.setText(_translate("MainWindow", "16"))
        item = self.tableWidget_2.item(2, 17)
        item.setText(_translate("MainWindow", "15"))
        item = self.tableWidget_2.item(2, 18)
        item.setText(_translate("MainWindow", "14"))
        item = self.tableWidget_2.item(2, 19)
        item.setText(_translate("MainWindow", "13"))
        item = self.tableWidget_2.item(2, 20)
        item.setText(_translate("MainWindow", "12"))
        item = self.tableWidget_2.item(2, 21)
        item.setText(_translate("MainWindow", "11"))
        item = self.tableWidget_2.item(2, 22)
        item.setText(_translate("MainWindow", "10"))
        item = self.tableWidget_2.item(2, 23)
        item.setText(_translate("MainWindow", "9"))
        item = self.tableWidget_2.item(2, 24)
        item.setText(_translate("MainWindow", "8"))
        item = self.tableWidget_2.item(2, 25)
        item.setText(_translate("MainWindow", "7"))
        item = self.tableWidget_2.item(2, 26)
        item.setText(_translate("MainWindow", "6"))
        item = self.tableWidget_2.item(2, 27)
        item.setText(_translate("MainWindow", "5"))
        item = self.tableWidget_2.item(2, 28)
        item.setText(_translate("MainWindow", "4"))
        item = self.tableWidget_2.item(2, 29)
        item.setText(_translate("MainWindow", "3"))
        item = self.tableWidget_2.item(2, 30)
        item.setText(_translate("MainWindow", "2"))
        item = self.tableWidget_2.item(2, 31)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget_2.item(2, 32)
        item.setText(_translate("MainWindow", "0"))
        item = self.tableWidget_2.item(3, 0)
        item.setText(_translate("MainWindow", "Вес бита"))
        item = self.tableWidget_2.item(3, 1)
        item.setText(_translate("MainWindow", "256"))
        item = self.tableWidget_2.item(3, 2)
        item.setText(_translate("MainWindow", "128"))
        item = self.tableWidget_2.item(3, 3)
        item.setText(_translate("MainWindow", "64"))
        item = self.tableWidget_2.item(3, 4)
        item.setText(_translate("MainWindow", "32"))
        item = self.tableWidget_2.item(3, 5)
        item.setText(_translate("MainWindow", "16"))
        item = self.tableWidget_2.item(3, 6)
        item.setText(_translate("MainWindow", "8"))
        item = self.tableWidget_2.item(3, 7)
        item.setText(_translate("MainWindow", "4"))
        item = self.tableWidget_2.item(3, 8)
        item.setText(_translate("MainWindow", "2"))
        item = self.tableWidget_2.item(3, 9)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget_2.item(3, 10)
        item.setText(_translate("MainWindow", "0.5"))
        item = self.tableWidget_2.item(3, 11)
        item.setText(_translate("MainWindow", "0.25"))
        item = self.tableWidget_2.item(3, 12)
        item.setText(_translate("MainWindow", "0.125"))
        item = self.tableWidget_2.item(3, 13)
        item.setText(_translate("MainWindow", "0.0625"))
        item = self.tableWidget_2.item(3, 14)
        item.setText(_translate("MainWindow", "0.0625"))
        item = self.tableWidget_2.item(3, 15)
        item.setText(_translate("MainWindow", "0.0625"))
        item = self.tableWidget_2.item(3, 16)
        item.setText(_translate("MainWindow", "0.0625"))
        item = self.tableWidget_2.item(3, 17)
        item.setText(_translate("MainWindow", "0.0625"))
        item = self.tableWidget_2.item(3, 18)
        item.setText(_translate("MainWindow", "0.0625"))
        item = self.tableWidget_2.item(3, 19)
        item.setText(_translate("MainWindow", "0.0625"))
        item = self.tableWidget_2.item(3, 20)
        item.setText(_translate("MainWindow", "0.0625"))
        item = self.tableWidget_2.item(3, 21)
        item.setText(_translate("MainWindow", "0.0625"))
        item = self.tableWidget_2.item(3, 22)
        item.setText(_translate("MainWindow", "0.0625"))
        item = self.tableWidget_2.item(3, 23)
        item.setText(_translate("MainWindow", "0.0625"))
        item = self.tableWidget_2.item(3, 24)
        item.setText(_translate("MainWindow", "0.0625"))
        item = self.tableWidget_2.item(3, 25)
        item.setText(_translate("MainWindow", "0.0625"))
        item = self.tableWidget_2.item(3, 26)
        item.setText(_translate("MainWindow", "0.0625"))
        item = self.tableWidget_2.item(3, 27)
        item.setText(_translate("MainWindow", "0.0625"))
        item = self.tableWidget_2.item(3, 28)
        item.setText(_translate("MainWindow", "0.0625"))
        item = self.tableWidget_2.item(3, 29)
        item.setText(_translate("MainWindow", "0.0625"))
        item = self.tableWidget_2.item(3, 30)
        item.setText(_translate("MainWindow", "0.0625"))
        item = self.tableWidget_2.item(3, 31)
        item.setText(_translate("MainWindow", "0.0625"))
        item = self.tableWidget_2.item(3, 32)
        item.setText(_translate("MainWindow", "0.0625"))
        item = self.tableWidget_2.item(4, 0)
        item.setText(_translate("MainWindow", "бит"))
        self.tableWidget_2.setSortingEnabled(__sortingEnabled)

class Ui_MainWindow3(object):

    def eval(self):

        print(float(self.lineEdit.text()))
        self.bin = doubleToBinary(float(self.lineEdit.text()))

        if (len(self.bin) == 63): self.bin = "0" + self.bin
        print(self.bin)
        self.tableWidget.setItem(1,0, QTableWidgetItem(str(self.bin[0])))
        self.tableWidget.setItem(1, 1, QTableWidgetItem(str(int(self.bin[1:11],2))))
        self.tableWidget.setItem(1, 2, QTableWidgetItem(str(int(self.bin[12:],2))))
        try:
            self.lineEdit_2.setText(self.lineEdit.text())
        except Exception as err: print(err)

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(591, 332)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(270, 50, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.eval)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 30, 141, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(50, 220, 121, 16))
        self.label_2.setObjectName("label_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(50, 240, 113, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(30, 50, 113, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setEnabled(False)
        self.tableWidget.setGeometry(QtCore.QRect(60, 110, 501, 71))
        self.tableWidget.setRowCount(2)
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setObjectName("tableWidget")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 0, item)
        self.tableWidget.horizontalHeader().setVisible(False)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(160)
        self.tableWidget.horizontalHeader().setHighlightSections(True)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(26)
        self.tableWidget.verticalHeader().setVisible(False)
        self.tableWidget.verticalHeader().setDefaultSectionSize(31)
        self.tableWidget.verticalHeader().setMinimumSectionSize(24)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "double float"))
        self.pushButton.setText(_translate("MainWindow", "Перевод"))
        self.label.setText(_translate("MainWindow", "Число"))
        self.label_2.setText(_translate("MainWindow", "Обратный перевод"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("MainWindow", "Знак (63)"))
        item = self.tableWidget.item(0, 1)
        item.setText(_translate("MainWindow", "Характеристика (62-52)"))
        item = self.tableWidget.item(0, 2)
        item.setText(_translate("MainWindow", "Мантиса (51-0)"))
        self.tableWidget.setSortingEnabled(__sortingEnabled)

class Ui_MainWindow4(object):

    def eval(self):
        try:
            self.s = ord(self.lineEdit.text()[0])
            self.lineEdit_2.setText(str(self.s))
            print(self.s)
            print(bin(self.s))
            self.s = "0"*(16+2-len(bin(self.s))) + bin(self.s)[2:]
            print(self.s)
            for i in range(4):
                self.a = self.s[4*i:4*(i+1)]
                self.tableWidget.setItem(1, i+1, QTableWidgetItem(str(self.a)))
                self.tableWidget.setItem(2, i+1, QTableWidgetItem(str(int(self.a,2))))
        except Exception as err: print(err)



    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(531, 250)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(50, 60, 113, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(220, 60, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.eval)
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setEnabled(False)
        self.tableWidget.setGeometry(QtCore.QRect(10, 100, 511, 121))
        self.tableWidget.setRowCount(3)
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setObjectName("tableWidget")
        item = QtWidgets.QTableWidgetItem();        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem();        self.tableWidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem();        self.tableWidget.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem();        self.tableWidget.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem();        self.tableWidget.setItem(0, 4, item)
        item = QtWidgets.QTableWidgetItem();        self.tableWidget.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem();        self.tableWidget.setItem(2, 0, item)
        self.tableWidget.horizontalHeader().setVisible(False)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(100)
        self.tableWidget.horizontalHeader().setHighlightSections(True)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(26)
        self.tableWidget.verticalHeader().setVisible(False)
        self.tableWidget.verticalHeader().setDefaultSectionSize(31)
        self.tableWidget.verticalHeader().setMinimumSectionSize(24)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 40, 141, 16))
        self.label.setObjectName("label")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(340, 60, 113, 20))
        self.lineEdit_2.setText("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(340, 40, 121, 16))
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "char"))
        self.pushButton.setText(_translate("MainWindow", "Перевод"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False);        item = self.tableWidget.item(0, 0)
        item.setText(_translate("MainWindow", "Тетрады"));        item = self.tableWidget.item(0, 1)
        item.setText(_translate("MainWindow", "Тетрада 3 (15-12)"));        item = self.tableWidget.item(0, 2)
        item.setText(_translate("MainWindow", "Тетрада 2 (11-8)"));        item = self.tableWidget.item(0, 3)
        item.setText(_translate("MainWindow", "Тетрада 2 (7-4)"));        item = self.tableWidget.item(0, 4)
        item.setText(_translate("MainWindow", "Тетрада 1 (3-1)"));        item = self.tableWidget.item(1, 0)
        item.setText(_translate("MainWindow", "Биты"));        item = self.tableWidget.item(2, 0)
        item.setText(_translate("MainWindow", "16- цифра"))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.label.setText(_translate("MainWindow", "Символ"))
        self.label_2.setText(_translate("MainWindow", "Код"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
